import type { PersistenceContract } from '../../types';
import {
  BRANDING_CONTRACT,
  COMPANY_MASTER_CONTRACT,
  COUNTRY_CONTRACT,
  DEAL_TYPE_CONTRACT,
  EXPENSE_CATEGORY_CONTRACT,
  INDUSTRY_CONTRACT,
  INVOICE_CONFIGURATION_CONTRACT,
  NOTIFICATION_CONFIGURATION_CONTRACT,
  OPPORTUNITY_SOURCE_CONTRACT,
  PAYMENT_METHOD_CONTRACT,
  RENEWAL_FREQUENCY_CONTRACT,
  STAGE_MASTER_CONTRACT,
  STATE_CONTRACT,
} from '../../modules/masters/contracts/master.contracts';
import {
  CUSTOMERS_CONTRACT,
  DEAL_COMPONENTS_CONTRACT,
  DEALS_CONTRACT,
  DOCUMENTS_CONTRACT,
  INVOICES_CONTRACT,
  PAYMENTS_CONTRACT,
} from '../../types/persistence.contracts';

/**
 * Canonical master worksheet contracts used by Bootstrap + HeaderManager.
 * Tab names preserve Sprint 3 MASTER_SHEET_TABS (MasterCompany, MasterStages, …).
 */
export const BOOTSTRAP_MASTER_CONTRACTS: readonly PersistenceContract[] = [
  COMPANY_MASTER_CONTRACT,
  COUNTRY_CONTRACT,
  STATE_CONTRACT,
  INDUSTRY_CONTRACT,
  OPPORTUNITY_SOURCE_CONTRACT,
  STAGE_MASTER_CONTRACT,
  DEAL_TYPE_CONTRACT,
  PAYMENT_METHOD_CONTRACT,
  EXPENSE_CATEGORY_CONTRACT,
  RENEWAL_FREQUENCY_CONTRACT,
  INVOICE_CONFIGURATION_CONTRACT,
  BRANDING_CONTRACT,
  NOTIFICATION_CONFIGURATION_CONTRACT,
] as const;

/** Business worksheets provisioned alongside masters (Customers sheet is singular for Opp+Customer). */
export const BOOTSTRAP_BUSINESS_CONTRACTS: readonly PersistenceContract[] = [
  CUSTOMERS_CONTRACT,
  DOCUMENTS_CONTRACT,
  DEALS_CONTRACT,
  DEAL_COMPONENTS_CONTRACT,
  INVOICES_CONTRACT,
  PAYMENTS_CONTRACT,
] as const;

export const BOOTSTRAP_CONTRACTS: readonly PersistenceContract[] = [
  ...BOOTSTRAP_MASTER_CONTRACTS,
  ...BOOTSTRAP_BUSINESS_CONTRACTS,
] as const;

export const BOOTSTRAP_REQUIRED_TAB_NAMES: readonly string[] =
  BOOTSTRAP_MASTER_CONTRACTS.map((contract) => contract.tabName);

export const DEFAULT_SHEET1_TITLE = 'Sheet1';
